src/routes/tools/BaseConverter.vue, src/routes/tools/UuidGenerator.vue, src/utils/helpers.js
`isInt` shouldn't be able to return true when entering a string.
Luckily Vue can automatically cast the input of a textfield to a number, so you don't have to worry about that at all.
Documented here:
https://vuejs.org/v2/guide/forms.html#number
=> Use vue-typecast

src/tools/date-time-converter/date-time-converter.vue
This doesn't really add any significant value or fix anything, but only simplifies the code a bit.
- adds a TypeScript type for the formats array
- DRYs the most common `toDate` variant
=> refactor: add a format type and use shorthand assignment

.vscode/extensions.json
The recommended extensions have changed ownership and now VS Code shows a notification that the ones listed in the json file are not found in the marketplace.
[Volar](https://marketplace.visualstudio.com/items?itemName=Vue.volar)
[TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)
=> fix: update recommended extension ids

.prettierrc.json, src/tools/hash-text/hash-text.vue
Instead of showing a select dropdown - compute all hashes at the same time and have a copy-able input.
(I've also added a very basic prettier config, which tries to make the least amount of changes when re-formatting)
=> Compute all hashes at the same time instead of using a select

src/tools/device-information/device-information.vue
I was checking out your site, and really like it! already added to my bookmarks, and when I was on the Device Information page I noticed the `p` and `y` in the words 1 dppx and landscape-primary were cut off and my ocd kicked in to tweak it.
The fix was to remove the line height set on the value, and then to keep the spacing how it was just moving it up 5px seemed to do the trick.
I'm using Firefox 102.0.1 on Windows 11. I'll attach some pics so you can see the before and after.
I've never messed with vue, but after looking at this file here ya make me want to check it out more. I love how its keeping it all together in one file.
Might also need to rebuild it the site after this change, but you get the point. 
Awesome site!
Before:
After
=> Device information page styling fix

src/composable/validation.ts, src/tools/index.ts, src/tools/ipv6-ula-generator/index.ts, src/tools/ipv6-ula-generator/ipv6-ula-generator.vue, src/tools/mac-address-lookup/mac-address-lookup.vue, src/utils/macAddress.ts
This new tool generates a random unique ula based on the current timestamp and the provided mac address.
An ULA is your "secondary" IPV6-Address only for internal use. It can also be used as a backup address if your provider gets offline and your Prefix-IPs are not longer valid.Also you can create the most of your internal firewall rules based on your ULAs.
=> feat(ipv6-ula-generator): new tool: generate ula based on timestamp and mac address

netlify.toml
When deploying to Netlify without this config file, you will encounter 404 problems when reloading the page.
=> Netlify deployment support

src/tools/chmod-calculator/chmod-calculator.service.test.ts, src/tools/chmod-calculator/chmod-calculator.service.ts, src/tools/chmod-calculator/chmod-calculator.vue
Added the symbolic representation (rwxrwxrwx) to the chmod-calculator. Also added relevant tests.
Somewhat addresses #418. This is my first time working with vue, so was not quite up to the task of implementing the request entirely.
=> Added symbolic representation to chmod-calculator

src/composable/copy.ts
=> fix(emoji picker): fix copy button

src/tools/eta-calculator/eta-calculator.vue
The current example makes no sense/is incorrect:
`if you wash 3 plates in 5 minutes and you have 500 plates to wash, it will take you 5 hours and 10 minutes to wash them all`
500 plates / 3 plates per time unit = 166.66... time units * 5 minutes = 833.33... minutes total time. (= 13.88... hours, not 5h 10m).
New example:
`if you wash 5 plates in 3 minutes and you have 500 plates to wash, it will take you 5 hours to wash them all`
500 plates / 5 plates per time unit = 100 time units * 3 minutes = 300 minutes = 5 hours
=> Corrected example for ETA calculation.

locales/zh.yml
=> feat(i18n): improve chinese i18n

README.md
It seems that the command to create a new tool was updated about a month ago but wasn't reflected in the README.md file.
This pull request fixes that :)
=> Updated tool command in readme

src/tools/camera-recorder/camera-recorder.vue
Issue:
For the camera recorder, the camera will stay turned on after switching between tools/pages.
A full refresh of the page is required to stop it
Fix:
Stop the media stream when user navigates away from the camera recorder tool
=> fix: stop camera recorder

src/tools/jwt-parser/jwt-parser.service.ts
fixes #798 support of claim array values (was shown "[Object]" before)
=> fix jwt claim array support

components.d.ts, src/tools/index.ts, src/tools/text-to-unicode/index.ts, src/tools/text-to-unicode/text-to-unicode.e2e.spec.ts, src/tools/text-to-unicode/text-to-unicode.service.test.ts, src/tools/text-to-unicode/text-to-unicode.service.ts, src/tools/text-to-unicode/text-to-unicode.vue
- Added `convertTextToUnicode` Function: This utility converts a given plain text string into its Unicode escape sequence representation, ensuring that the text can be safely transmitted or stored in environments that might not support certain characters or encodings.
- Added `convertUnicodeToText` Function: Complementing the above utility, this function converts Unicode escape sequences back into their original plain text form, allowing for the accurate retrieval and display of the stored or transmitted information.
=> feat(new-tool): Implement Unicode Conversion Utilities

locales/vi.yml, src/modules/i18n/components/locale-selector.vue, src/tools/text-to-unicode/text-to-unicode.vue
- Added `Vietnamese Language Support`: Implemented internationalization (i18n) for the Vietnamese language.
- Chore `Text-to-Unicode Conversion Tool Typo Fix`: Corrected a typo in the tool's interface that affected the tool's instructional text. This fix improves clarity and ensures that the tool's functionality is accurately communicated to the users.
=> feat(i18n): added vietnamese translation

src/tools/integer-base-converter/integer-base-converter.model.test.ts, src/tools/integer-base-converter/integer-base-converter.model.ts
Currently, integer base converter does not support "bigint", thus resulting in "non failing" totally wrong conversions. See screen capture (ie, decimal conversion does not correspond to input)
=> fix(integer base converter): support bigint

src/components/FormatTransformer.vue
This PR fixed a style issue of component FormatTransformer, which is used in tools `json-to-toml`, `json-to-yaml` and so on.
This PR fixed issue https://github.com/CorentinTh/it-tools/issues/780
=> fix(format-transformer): set overflow for output area width

src/tools/html-wysiwyg-editor/editor/menu-bar.vue
Fix: https://github.com/CorentinTh/it-tools/issues/1342
- fixed typo in menu-bar.vue
##
Since PRs are a bit backed up on https://github.com/CorentinTh/it-tools you can use my image in your docker-compose file if you want this functionality along with my other additions until the main branch has been updated:
- reorder favorites with drag and drop: (https://github.com/CorentinTh/it-tools/pull/1360)
- AI prompt splitter: (https://github.com/CorentinTh/it-tools/pull/1357)
- multi-link downloader: (https://github.com/CorentinTh/it-tools/pull/1354)
- image resizer: (https://github.com/CorentinTh/it-tools/pull/1361)
- JSON String converter: (https://github.com/CorentinTh/it-tools/pull/1351)
**docker image:**
```
ghcr.io/gitmotion/it-tools:latest
```
- you may need to clear cache and hard reload …
=> feat(html-wysiwyg-editor) h3 fix

README.md
@CorentinTh 
Allow auto refresh of stale contributors graph onload of main repository page
(if you'd like to have that happen that is)
> **Before:**
> **After:**
=> fix(readme) allow auto refresh of stale contributors graph

src/layouts/tool.layout.vue, src/tools/tools.store.ts
@CorentinTh
Bug Fix: https://github.com/CorentinTh/it-tools/issues/1365
**- previously was not passing the route path to the object when passing as tool:**
**- this also caused it to add nulls to the favoritesToolName in local storage:**
**- adding the path should prevent nulls from getting add now but also added if check before adding directly to the store:**
=> fix(FavoriteButton) fix favorite button funtionality on tool page
