README.md, src/router.js, src/routes/tools/BaseConverter.vue, src/utils/helpers.js
- prevent non integer base in BaseConverter
- add 404 page in roadmap
- removed history mode for direct url access
Closes #3.
=> fix: prevent non integer base in BaseConverter

CHANGELOG.md, README.md, package-lock.json, package.json, src/routes/tools/UuidGenerator.vue
=> [feat] generate multiples uuid

src/utils/helpers.js
Compare performance: https://jsperf.com/is-damn-integer
=> Use Number.isInteger

CHANGELOG.md, package-lock.json, package.json, src/routes/tools/UuidGenerator.vue, src/utils/helpers.js
=> better isInt + UuidGenerator quantity validation rules

src/tools/hash-text/hash-text.service.test.ts, src/tools/hash-text/hash-text.service.ts, src/tools/hash-text/hash-text.vue
=> feat(hash-text): digest base selector

src/components/TextareaCopyable.vue, src/tools/index.ts, src/tools/json-viewer/json-viewer.vue, src/tools/sql-prettify/sql-prettify.vue, src/tools/svg-placeholder-generator/index.ts, src/tools/svg-placeholder-generator/svg-placeholder-generator.vue
=> Svg placeholder generator

.eslintrc.cjs, .prettierrc, package-lock.json, package.json, src/tools/hmac-generator/hmac-generator.vue, src/tools/hmac-generator/index.ts, src/tools/index.ts
=> HMAC generator 

src/tools/index.ts, src/tools/json-minify/index.ts, src/tools/json-minify/json-minify.vue
=> feat(new-tool): json minify

.github/workflows/docker-release.yml
I have added ARM64 Support to the Docker Image
=> arm64 as supported plattform added

src/tools/otp-code-generator-and-validator/otp-code-generator-and-validator.vue
=> refactor(otp-generator): no more barcode color invertion

src/tools/otp-code-generator-and-validator/otp-code-generator-and-validator.vue, src/tools/otp-code-generator-and-validator/otp.service.test.ts, src/tools/otp-code-generator-and-validator/otp.service.ts
=> refactor(otp-generator): coerce lowercase secret characters to uppercase

src/tools/rsa-key-pair-generator/rsa-key-pair-generator.service.ts
=> fix(rsa-key-pair-generator): correct prime web worker url

Dockerfile, nginx.conf
=> fix(docker): nginx config to redirect to index.html

src/config.ts, src/pages/Home.page.vue
=> feat(config): hide the banner by default

src/composable/computedRefreshable.ts, src/tools/rsa-key-pair-generator/rsa-key-pair-generator.vue
=> feat(rsa-key-pair-generator): refresh certs button

src/tools/json-viewer/json-viewer.vue, src/tools/json-viewer/json.models.test.ts, src/tools/json-viewer/json.models.ts
=> feat(json-prettify): sort keys

src/components/CollapsibleToolMenu.vue, src/layouts/base.layout.vue
=> feat(menu): collapsible categories

src/composable/computedRefreshable.ts, src/tools/otp-code-generator-and-validator/otp-code-generator-and-validator.vue
=> fix(otp-generator): better computation of token

src/config.ts, src/plugins/plausible.plugin.ts
=> feat(plausible): disable plausible instance for self hosted instance

src/tools/qr-code-generator/qr-code-generator.vue, src/tools/qr-code-generator/useQRCode.ts
=> refactor(qr-code): multiline input

components.d.ts, package.json, pnpm-lock.yaml, src/tools/index.ts, src/tools/mac-address-lookup/index.ts, src/tools/mac-address-lookup/mac-address-lookup.vue, src/tools/mac-address-lookup/oui.d.ts
=> feat(new-tool): mac address lookup

src/tools/index.ts, src/tools/ipv4-address-converter/index.ts, src/tools/ipv4-address-converter/ipv4-address-converter.service.test.ts, src/tools/ipv4-address-converter/ipv4-address-converter.service.ts, src/tools/ipv4-address-converter/ipv4-address-converter.vue
=> feat(new-tool): ipv4 address converter

package.json, pnpm-lock.yaml, src/tools/index.ts, src/tools/json-to-yaml-converter/index.ts, src/tools/json-to-yaml-converter/json-to-yaml.e2e.spec.ts, src/tools/json-to-yaml-converter/json-to-yaml.vue, src/tools/yaml-to-json-converter/index.ts, src/tools/yaml-to-json-converter/yaml-to-json.e2e.spec.ts, src/tools/yaml-to-json-converter/yaml-to-json.vue
=> feat(new-tool): yaml and json converters

playwright.config.ts, src/composable/validation.ts, src/tools/date-time-converter/date-time-converter.e2e.spec.ts, src/tools/date-time-converter/date-time-converter.models.test.ts, src/tools/date-time-converter/date-time-converter.models.ts, src/tools/date-time-converter/date-time-converter.types.ts, src/tools/date-time-converter/date-time-converter.vue
=> refactor(date-converter): improved ux and layout

src/tools/uuid-generator/uuid-generator.vue
=> refactor(uuid-generator): prevent NaN in quantity

src/tools/phone-parser-and-formatter/phone-parser-and-formatter.models.ts, src/tools/phone-parser-and-formatter/phone-parser-and-formatter.vue
=> fix(phone-parser): use default country code

auto-imports.d.ts, src/components/FormatTransformer.vue, src/tools/base64-file-converter/base64-file-converter.vue, src/tools/base64-string-converter/base64-string-converter.vue, src/tools/date-time-converter/date-time-converter.vue, src/tools/ipv4-range-expander/ipv4-range-expander.vue, src/tools/json-diff/json-diff.vue, src/tools/mac-address-lookup/mac-address-lookup.vue, src/ui/c-input-text/c-input-text.vue, src/utils/macAddress.ts
=> refactor(ui): replaced some n-input with c-input-text

src/tools/ipv4-address-converter/ipv4-address-converter.vue
=> fix(ipv4-converter): removed readonly on input

src/tools/phone-parser-and-formatter/phone-parser-and-formatter.vue
=> feat(phone-parser): searchable country code select

src/ui/c-input-text/c-input-text.vue
=> refactor(c-input-text): force usage of props with default

.eslintrc-auto-import.json, auto-imports.d.ts, locales/en.yml, locales/fr.yml, package.json, pnpm-lock.yaml, src/main.ts, src/pages/Home.page.vue, src/plugins/i18n.plugin.ts, tsconfig.app.json, vite.config.ts
Related to #269
Ping @jmmanzano
=> chore(i18n): setup i18n plugin config

components.d.ts, src/tools/index.ts, src/tools/json-to-csv/index.ts, src/tools/json-to-csv/json-to-csv.e2e.spec.ts, src/tools/json-to-csv/json-to-csv.service.test.ts, src/tools/json-to-csv/json-to-csv.service.ts, src/tools/json-to-csv/json-to-csv.vue
=> feat(new-tool): json to csv converter

components.d.ts, src/tools/index.ts, src/tools/percentage-calculator/index.ts, src/tools/percentage-calculator/percentage-calculator.e2e.spec.ts, src/tools/percentage-calculator/percentage-calculator.vue
Adds a new percentage calculator tool
<p>&nbsp;</p>
=> feat(new tool): percentage calculator

src/tools/mime-types/mime-types.vue
=> fix(mime-types): typos

locales/en.yml, src/layouts/tool.layout.vue, src/plugins/i18n.plugin.ts, src/tools/token-generator/locales/en.yml, src/tools/token-generator/locales/fr.yml, src/tools/token-generator/token-generator.tool.vue
=> chore(i18n): tool scoped locales

.vscode/extensions.json, README.md
=> docs(ide): updated vscode extensions settings

src/tools/json-viewer/json-viewer.vue
Missed it in https://github.com/CorentinTh/it-tools/pull/476
=> style(JSON viewer): input monospace font

components.d.ts, pnpm-lock.yaml, src/components/FavoriteButton.vue, src/components/InputCopyable.vue, src/components/NavbarButtons.vue, src/components/SpanCopyable.vue, src/components/TextareaCopyable.vue, src/layouts/base.layout.vue, src/tools/benchmark-builder/dynamic-values.vue, src/tools/html-wysiwyg-editor/editor/menu-bar-item.vue, src/tools/otp-code-generator-and-validator/otp-code-generator-and-validator.vue, src/tools/otp-code-generator-and-validator/token-display.vue, src/tools/user-agent-parser/user-agent-result-cards.vue, src/ui/c-tooltip/c-tooltip.demo.vue, src/ui/c-tooltip/c-tooltip.vue
=> refactor(ui): switched from naive tooltip components to custom ones

src/pages/About.vue
=> refactor(ui): removed n-p components in about page

components.d.ts, src/tools/index.ts, src/tools/text-to-binary/index.ts, src/tools/text-to-binary/text-to-binary.e2e.spec.ts, src/tools/text-to-binary/text-to-binary.models.test.ts, src/tools/text-to-binary/text-to-binary.models.ts, src/tools/text-to-binary/text-to-binary.vue
=> feat(new tool): text to ascii converter

package.json, pnpm-lock.yaml
Updating @sindresorhus/slugify to the latest version fixes the issue #593
=> fix(deps): fix issue on slugify (#593)

locales/en.yml, src/pages/404.page.vue
404 page support for internationalization
=> feat(i18n): 404 page

locales/en.yml, src/pages/About.vue
about page support for internationalization
=> feat(i18n): about page

locales/en.yml, src/components/ToolCard.vue
tool card support for internationalization
=> feat(i18n): tool card

src/plugins/i18n.plugin.ts
using internationalized configuration in .ts files
=> feat(i18n): support for i18n in .ts files

src/tools/token-generator/index.ts, src/tools/token-generator/locales/en.yml, src/tools/token-generator/token-generator.tool.vue
token generator support for internationalization
=> feat(i18n): token generator

.dockerignore, Dockerfile
=> refactor(docker): improved docker config

src/tools/color-converter/color-converter.e2e.spec.ts, src/tools/color-converter/color-converter.models.test.ts, src/tools/color-converter/color-converter.models.ts, src/tools/color-converter/color-converter.vue
=> refactor(color-converter): improved color-converter UX

src/tools/date-time-converter/date-time-converter.e2e.spec.ts, src/tools/date-time-converter/date-time-converter.models.test.ts, src/tools/date-time-converter/date-time-converter.models.ts, src/tools/date-time-converter/date-time-converter.vue
=> feat(date-converter): added excel date time format

src/modules/command-palette/command-palette.vue
=> feat(command-palette): clear prompt on palette close

Dockerfile
Fixes https://github.com/CorentinTh/it-tools/issues/714
=> Fix: dockerfile - revert replacement of nginx image with non-privileged one

.github/workflows/docker-nightly-release.yml, .github/workflows/releases.yml
=> chore(docker): added armv7 plateform for docker releases

src/tools/bcrypt/bcrypt.vue
=> refactor(bcrypt): fix input label align

src/tools/token-generator/index.ts
=> refactor(token): added password in token generator keywords

src/tools/case-converter/case-converter.vue
=> refactor(case converter): no split on lowercase, uppercase and mocking case

src/composable/downloadBase64.test.ts, src/composable/downloadBase64.ts
=> fix(base64-file-converter): fix downloading of index.html content without data preambula

src/tools/uuid-generator/index.ts, src/tools/uuid-generator/uuid-generator.vue, src/ui/c-buttons-select/c-buttons-select.demo.vue, src/ui/c-buttons-select/c-buttons-select.vue
=> refactor(uuid generator): uuid version picker

locales/en.yml, src/components/FavoriteButton.vue, src/layouts/base.layout.vue
Add Navbar items tooltip and favoriteButton i18n
=> feat(i18n): add tooltip and favoriteButton i18n

locales/pt.yml
=> Add Portuguese translation

locales/en.yml
This commit fixes errors in the possessive vs. contraction form of "it," clarifies the description verbiage in some tools, and provides some general cleanup.
=> fix(language): English language cleanup

locales/de.yml, src/modules/i18n/components/locale-selector.vue
Add the German translation.
---
=> feat(i18n): German translation

package.json, pnpm-lock.yaml, src/composable/downloadBase64.ts, src/tools/base64-file-converter/base64-file-converter.vue, src/utils/base64.test.ts, src/utils/base64.ts
Use js-base64 to handle non ascii text and ignore whitespaces
Fix https://github.com/CorentinTh/it-tools/issues/879 and https://github.com/CorentinTh/it-tools/issues/409 and #1092
Add filename and extension (auto filled if data url) to allow downloading with right extension and filename
Fix https://github.com/CorentinTh/it-tools/issues/788
Add preview image : Fix https://github.com/CorentinTh/it-tools/issues/594. Taken from https://github.com/CorentinTh/it-tools/pull/595 (thanks @SAF2k)
=> Base64 Enhancements (converter and file converter)

src/tools/jwt-parser/jwt-parser.vue
=> fix(JWT Parser): UI overflow on small screen

package.json, src/composable/debouncedref.ts, src/tools/emoji-picker/emoji-picker.vue
=> fix(Emoji picker): fix lags

src/tools/lorem-ipsum-generator/lorem-ipsum-generator.vue
I added a button to **refresh** the text since I was using the generator several times and in order to generate another text I had to change some of the options and it became tedious.
=> Add button to refresh text lorem-ipsum

src/tools/tools.store.ts
=> fix: store favorites regardless of languages

locales/no.yml, src/modules/i18n/components/locale-selector.vue
Language code: no
Official Name: Norwegian
Native Name: Norsk
=> Added Norwegian language support
